name: tcc_teste
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.1
  flutter_map: ^6.0.0
  flutter_colorpicker: ^1.0.3
  mysql1: ^0.20.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/home/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/splashScreen/splashScreen.png 
    - assets/splashScreen/splashDois.png 
    - assets/home/logo.png
    - assets/home/icons/location.png
    - assets/home/icons/busStop.png
    - assets/home/icons/bus.png
    - assets/home/icons/clock.png